# ---------------------------------------------------------------------------
# Stable features that we customize locally
# ---------------------------------------------------------------------------
max_width = 80
use_small_heuristics = "max"
unstable_features = true

#
# ---------------------------------------------------------------------------
# Unstable features that we customize locally
# ---------------------------------------------------------------------------
#
# We would like to use "wrap_comments = true" and "comment_width = 80", but
# there are several issues with our use of it today, including rustfmt#4079 and
# rustfmt#4020.
#
# "overflow_delimited_expr" and "struct_lit_single_line" are both fairly minor,
# but improve readability.
#
format_strings = true
overflow_delimited_expr = true
struct_lit_single_line = false

#
# ---------------------------------------------------------------------------
# Below are all other flags that we do NOT customize.  We specify these
# explicitly here to minimize churn if the upstream defaults change.  If you
# modify any of these, move them above this line!
#
# The following can be generated by starting with:
#
#    rustfmt +nightly --print-config=default
#
# and removing anything that we've configured above.
# ---------------------------------------------------------------------------
#
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
indent_style = "Block"
wrap_comments = false
format_code_in_doc_comments = false
comment_width = 80
normalize_comments = false
normalize_doc_attributes = false
license_template_path = ""
format_macro_matchers = false
format_macro_bodies = true
empty_item_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_layout = "Mixed"
merge_imports = false
reorder_imports = true
reorder_modules = true
reorder_impl_items = false
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
force_multiline_blocks = false
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
edition = "2018"
version = "One"
inline_attribute_width = 0
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = false
color = "Auto"
required_version = "1.4.15"
disable_all_formatting = false
skip_children = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
report_todo = "Never"
report_fixme = "Never"
ignore = []
emit_mode = "Files"
make_backup = false
